### ISSUE TITLE
Heading for Guidepost

### ISSUE THREAD

**Issue by mkaz** [sortabrilliant/guidepost#17]
Feature suggestion:

I'd like to be able to add a "Table of Contents" header to the Guidepost block but not have it show up in the Guidepost, which happens if I put a normal header above it.

Maybe could be done as a title element for the block?

**Comment by jrtashjian** [comment]
It definitely makes sense to add this in. I'll see about getting it added.

**Comment by jrtashjian** [comment]
@mkaz After a bit of a hiatus I've refactored this block entirely! It's now properly hooking into the data stores to get `core/headings` and any updates. I think for your request and now that the Group block exists, you can use the Group block to group a Heading and Guidepost block. This will work because Guidepost only builds the TOC with headings at the root of the document.

It didn't make sense to me to pull in headings from innerBlocks because they are used for things other than a page's navigation structure, for instance the Hero block in CoBlocks.
